### ISSUE TITLE
Ubermag contribution

### ISSUE THREAD

**Issue by marijanbeg** [ZhiyuZhang001/micromagnetic-simulation#2]
Hi @ZhiyuZhang001, we are delighted you are using Ubermag in your research :)

Ubermag is an open-source project, which we, researchers, have been developing for the community. We are very interested in people helping us by contributing to the code, implementing their own ideas, providing use cases, writing tutorials, reviewing documentation, reviewing pull requests,... the list is endless :) Would you (and/or any of your colleagues) be interested in becoming an Ubermag contributor? If yes, we will be organising an online workshop at some point in the future, where we will explain git, GitHub, pull requests, how to contribute to the code, and everything else necessary. We are looking forward to hearing from you.

**Comment by ZhiyuZhang001** [comment]
Thank you for your invitation. Some code have been completed  and I hope it can help people who need it. You can pull requests if you want.
